### ISSUE TITLE
Apache 2.0 License short name not in spdx format 

### ISSUE THREAD

**Issue by ufukhurriyetoglu** [snipsco/snips-nlu-parsers#32]
We have issue with license checkers due to license short name listed at 
https://github.com/snipsco/snips-nlu-parsers/blob/master/python/setup.py#L44

It should be Apache-2.0 as mentioned in https://spdx.org/licenses/Apache-2.0.html

**Comment by adrienball** [comment]
Thanks for reporting this, I updated the license name in the linked PR.

**Comment by ufukhurriyetoglu** [comment]
Thanks a lot!

**Comment by ufukhurriyetoglu** [comment]
@adrienball There is also a need to update 0.2.1 version. Sorry, I forget to mention this one. 

https://github.com/snipsco/snips-nlu-parsers/blob/lts-0.2.1.x/python/setup.py#L44
